[speech]
engine = "sapi"

[speech.sapi]
#voice = 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\MSTTS_V110_nlNL_Frank'
voice = { gender = "male", language = "0x413" }
volume = 100
rate = 0



[arduino]
board = "SparkFun:avr:promicro:cpu=16MHzatmega32U4"
port = "COM3"

[[arduino.sensors]]
pin = "A0"
label = "Links"
limits = [0, 1023]
thresholds = [33, 88]

[[arduino.sensors]]
pin = "A1"
label = "Rechts"
limits = [0, 1023]
thresholds = [33, 88]

[[arduino.sensors]]
pin = "A2"
label = "Bevestigen"
limits = [0, 1023]
thresholds = [33, 88]

# [[arduino.sensors]]
# pin = "A3"
# label = "Annuleren"
# limits = [0, 1023]
# thresholds = [33, 88]



[decoder]
confirm = 2
# cancel = 3

[decoder.scheme]
# Letters
"append:e" = [0]
"append:n" = [1]
"append:a" = [0, 0]
"append:t" = [0, 1]
"append:r" = [1, 0]
"append:i" = [1, 1]
"append:o" = [0, 0, 0]
"append:d" = [0, 0, 1]
"append:s" = [0, 1, 0]
"append:l" = [0, 1, 1]
"append:g" = [1, 0, 0]
"append:v" = [1, 0, 1]
"append:h" = [1, 1, 0]
"append:k" = [1, 1, 1]
"append:u" = [0, 0, 0, 0]
"append:m" = [0, 0, 0, 1]
"append:b" = [0, 0, 1, 0]
"append:p" = [0, 0, 1, 1]
"append:w" = [0, 1, 0, 0]
"append:j" = [0, 1, 0, 1]
"append:z" = [0, 1, 1, 0]
"append:c" = [0, 1, 1, 1]
"append:f" = [1, 0, 0, 0]
"append:x" = [1, 0, 0, 1]
"append:y" = [1, 0, 1, 0]
"append:q" = [1, 0, 1, 1]

# Speciaal
"append:ij" = [1, 1, 0, 0]
"append:,"  = [1, 1, 0, 1]
"question"  = [1, 1, 1, 0]
"delete"    = [1, 1, 1, 1]

# Cijfers
"append:1" = [0, 1, 1, 1, 1]
"append:2" = [0, 0, 1, 1, 1]
"append:3" = [0, 0, 0, 1, 1]
"append:4" = [0, 0, 0, 0, 1]
"append:5" = [0, 0, 0, 0, 0]
"append:6" = [1, 0, 0, 0, 0]
"append:7" = [1, 1, 0, 0, 0]
"append:8" = [1, 1, 1, 0, 0]
"append:9" = [1, 1, 1, 1, 0]
"append:0" = [1, 1, 1, 1, 1]

[decoder.prediction]
dictionary = "nl.json.gz"
suggestions = 10